export const APP_SCREENS = {
  EMAIL_SCREEN: 0,
  QUESTIONNAIRE: 1,
  TESTER_SCREEN: 2,
  FINISH_SCREEN: 3,
  REACT_POKUSY: 4,
};

export const T_STATES = {
  NEW: 'NEW',
  ROUND_PREPARED: 'ROUND_PREPARED',
  RUNNING: 'RUNNING',
  DELAYING: 'DELAYING',
  ROUND_PROCESSING: 'ROUND_PROCESSING',
  ALL_FINISHED: 'ALL_FINISHED',
}