export const TESTING_SESSION = 'session_dev_01'

export const APP_SCREENS = {
  EMAIL_SCREEN: 0,
  TESTER_SCREEN: 1,
  FINISH_SCREEN: 2,
  REACT_POKUSY: 3,
};

export const T_STATES = {
  NEW: 'NEW',
  ROUND_PREPARED: 'ROUND_PREPARED',
  RUNNING: 'RUNNING',
  DELAYING: 'DELAYING',
  ROUND_PROCESSING: 'ROUND_PROCESSING',
  ALL_FINISHED: 'ALL_FINISHED',
}